server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;
    root /var/www/html;
    index index.html;

    location /health {
        access_log off;
        return 200 "OK\n";
        add_header Content-Type text/plain;
    }

    # Static content by default
    location / {
        try_files $uri $uri/ =404;
    }

    # Load all snippets (jenkins.conf, etc.)
    include /etc/nginx/snippets/*.conf;
}
